import Foundation
import SwiftAgent

// MARK: - Phase 1: Objective Analysis

/// Response from objective analysis.
///
/// The LLM analyzes the objective and generates search keywords and Socratic questions.
/// Reference: AMD Framework (arXiv:2502.08557)
@Generable
public struct ObjectiveAnalysisResponse: Sendable {
    @Guide(description: "Keywords for search (English, search engine optimized)")
    public let keywords: [String]

    @Guide(description: "Specific questions to answer (clarification, assumption testing, implication exploration)")
    public let questions: [String]

    @Guide(description: "Criteria for determining information sufficiency")
    public let successCriteria: [String]
}

// MARK: - Phase 3: Content Review

/// Line range indicating where relevant information is located.
@Generable
public struct RelevantRange: Sendable {
    @Guide(description: "Start line number of relevant information")
    public let start: Int

    @Guide(description: "End line number of relevant information")
    public let end: Int
}

/// Response from content review.
///
/// Focuses on information extraction. Question verification is performed in Phase 4.
@Generable
public struct ContentReviewResponse: Sendable {
    @Guide(description: "Whether this content is relevant to the objective")
    public let isRelevant: Bool

    @Guide(description: "Extracted relevant information (concise, 100-300 chars)")
    public let extractedInfo: String

    @Guide(description: "Whether there are links worth deep crawling")
    public let shouldDeepCrawl: Bool

    @Guide(description: "Candidate links for deep crawling")
    public let priorityLinks: [PriorityLink]

    @Guide(description: "Line ranges containing relevant information")
    public let relevantRanges: [RelevantRange]
}

/// Priority link information for deep crawling.
@Generable
public struct PriorityLink: Sendable {
    @Guide(description: "Link index number (starting from 1)", .range(1...100))
    public let index: Int

    @Guide(description: "Relevance score (0.0-1.0)", .range(0.0...1.0))
    public let score: Double

    @Guide(description: "Reason for selecting this link")
    public let reason: String
}

// MARK: - Phase 3.5: DeepCrawl Review

/// Response from deep crawl content review.
///
/// Considers history to decide whether to continue deep crawling.
@Generable
public struct DeepCrawlReviewResponse: Sendable {
    @Guide(description: "Whether this content is relevant to the objective")
    public let isRelevant: Bool

    @Guide(description: "Extracted relevant information (concise, 100-300 chars)")
    public let extractedInfo: String

    @Guide(description: "Whether to continue deep crawling considering history")
    public let shouldContinue: Bool

    @Guide(description: "Reason for continue/stop decision")
    public let reason: String
}

// MARK: - Phase 4: Sufficiency Check

/// Response from sufficiency check.
@Generable
public struct SufficiencyCheckResponse: Sendable {
    @Guide(description: "Whether sufficient information has been gathered to achieve the objective")
    public let isSufficient: Bool

    @Guide(description: "Whether further information retrieval is difficult")
    public let shouldGiveUp: Bool

    @Guide(description: "Additional keywords to search (if insufficient)")
    public let additionalKeywords: [String]

    @Guide(description: "Reasoning for the decision (Markdown format)")
    public let reasonMarkdown: String

    @Guide(description: "Current success criteria (added, removed, or modified as needed)")
    public let successCriteria: [String]
}

// MARK: - Phase 5: Response Building

/// Response from final response generation.
///
/// Source URLs are added programmatically, not generated by the LLM.
@Generable
public struct FinalResponseBuildingResponse: Sendable {
    @Guide(description: "Final response to the objective (Markdown format)")
    public let responseMarkdown: String
}
